---
abstract: 'a framework to build intrusive high order proxies'
author:
  - 'Nuno Carvalho <smash@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Navegante
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  Test::More: 0
  URI::URL: 0
  XML::DT: 0.51
version: 0.02
