--- #YAML:1.0
name:                App-Navegante
version:             0.01
abstract:            a framework to build intrusive high order proxies
license:             ~
author:              
    - Nuno Carvalho <smash@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP::UserAgent:                HTTP::Request
    Test::More:                    0
    URI::URL:                      CGI
    XML::DT:                       0.51
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
